@startuml
title
Klassendiagramm Anwesenheitsliste
end title
' left to right direction
skinparam ranksep 150

header getter, setter und Konstuktor wurde nicht dargestellt!

class Person{
    -id : int
    -vorname : string
    -nachname : string
    -mail : string
    -organisationseinheit : Organisationseinheit
    +addAbwesenheit(abwesenheit : Abwesenheit)
    +removeAbwesenheit(abwesenheit : Abwesenheit)
    ' +getId()
    ' +getVorname()
    ' +getNachame()
    ' +getName()
    ' +getMail()
    ' +getOrganisationseinheit()
    ' +setId()
    ' +setVorname()
    ' +setNachame()
    ' +setName()
    ' +setMail()
    ' +setOrganisationseinheit()
}

class Leiter{
    -leitungsList : Organisationseinheit = []
    ' +getLeitung()
    ' +setLeitung()
}

class Organisationseinheit{
    -name : string
    -kürzel : string
    -personenListe : List = []
    +addPerson(person : Person, organisationseinheit : Organisationseinheit)
    +removeAngestellter(person : Person, organisationseinheit : Organisationseinheit)
}

class Abwesenheit{
    -id : int
    -start : date
    -ende : date
    -grund : Grund
    -kommentar : string
    +delete()
}

enum Grund{
    Urlaub
    Krankheit
    Home-Office
    Elternzeit
    Weiterbildung
}

class DatabaseConnector{
    -host : string
    -port : int
    -benutzer : string
    -passwort : string
    -connection : Object
    -createConnection(host : sting, port : int, benutzer : string, passwort : string)
    +getConnection()
    +closeConnection()
}



Person <|- Leiter
Organisationseinheit "1" -- "0..*" Person 
Organisationseinheit "1" - "1" Leiter 
Person "1" -- "1" Abwesenheit
' Grund ..> Abwesenheit
@enduml