@startuml Komponentendiagramm
title
Komponentendiagramm Mietverwaltung
end title
left to right direction

legend top left
  KeyCloak: "Keycloak provides user federation, strong authentication, 
  user management, fine-grained authorization, and more." https://www.keycloak.org/
  
  Flask: Python micro Framework zum erstellen Schnittstellen und mehr. https://flask.palletsprojects.com/en/3.0.x/
endlegend

database "PostgreSQL Server" {
    [PostgreSQL]<<component>>
    Psycopg -[PostgreSQL]
}

node "clients" {
    [Webbrowser]
}

node "Anwendungsserver"{
    [Flask App]<<component>>
    [Flask App] -up- REST

    [Mailserver] <<component>>
    [Mailserver]- SMTP
}

node "KeyCloak Server"{
    [KeyCloak] <<component>>
}

node "Webserver" {
    [React App] <<component>>
}

[React App]-- HTTPS
[React App]-- übersichts_export
[Flask App]--( Psycopg
[Flask App]-left-( SMTP
[Flask App]-right-( KeyCloakAdapter
[React App]--( REST
[Webbrowser]--( HTTPS
[KeyCloak]-left- KeyCloakAdapter
[React App]-( KeyCloakAdapter
@enduml