@startuml
title
Klassendiagramm Vermietung Vertragsverwaltung
end title

header getter, setter und Konstuktor wurden aus Gründen der Übersichtlichkeit nicht dargestellt

abstract Vertrag {
    -vertragStart : date
    -vertragEnde : date
    +getMietvertrag(dbConnector : DbConnector)
}

class Mietvertrag {
    +getMiethöhe(mietraum : Mietraum)
}

class Untermietvertrag {
    -miethöhe : double
    -untermieter : Untermieter
}

abstract Person {
    -vorname : string
    -nachname : string
    -gebutstag : date
    -mail : string
    -mietraum : Mietraum
    +getPerson(dbConnector : DbConnector)
}

class Mieter {
    -iban : string
    -mietvertrag : Mietvertrag
}

class Untermieter {
    -hauptmieter : Mieter
    -untermietvertrag : Untermietvertrag
}

class Mietraum {
    -qMeter : int
    -zimmer : double
    -qMeterPreis : double
    -mietraumStatus : MietraumStatus
    +getMietraum(dbConnector : DbConnector)
}

enum MietraumStatus {
    Gewerbe
    Privat
    Leerstand
}

class DbConnector {
    -host : string
    -port : int
    -benutzer : string
    -passwort : string
    -connection : Object
    +execute(query : string)
    +closeConnection()
}

' Vererbungen
Mietvertrag -|> Vertrag
Untermietvertrag -|> Vertrag
Mieter -|> Person
Untermieter -|> Person

' Assoziationen
Mieter "0..*"*--"1" Untermieter
Untermieter "1"--"1" Untermietvertrag
Mieter "1..*"--"1" Mietvertrag
Mietraum "1"--"0..*" Person 
Mietraum -- DbConnector
Person -right- DbConnector
Vertrag -up- DbConnector
@enduml